### ISSUE TITLE
llvm-cov Output to Cobertura XML

### ISSUE THREAD

**Issue by RLovelett** [SDGGiesbrecht/SDGSwift#329]
### Question

I've noticed that you've posted [a few messages](https://forums.swift.org/t/how-is-enable-code-coverage-intended-to-be-used/26296/6) over in [the Swift forums](https://forums.swift.org/t/proposed-changes-to-swift-5-code-coverage/24201/4) discussing Swift code coverage.

In one of them you even hint about this library being able to work directly with the JSON output from `llvm-cov`.

I'm interested in writing a utility to parse the JSON (or some other Swift code coverage artifact from `llvm-cov`) and convert it to Cobertura XML for use in my [GitLab CI pipelines](https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html).

I'm interested in how one might use [`TestCoverageReport`](https://sdggiesbrecht.github.io/SDGSwift/%F0%9F%87%A8%F0%9F%87%A6EN/Types/TestCoverageReport.html), if at all, to interpret the output from `llvm-cov`. In your opinion could you see a way to use the modules/types in this package provide a path to achieving the goal I have?

### Documentation Suggestion

The subject matter is a little dense here. Some guiding examples on how one might make use of some of the modules/types.

**Comment by SDGGiesbrecht** [comment]
So far, this library basically assumes you want to go straight from the package itself to a strongly typed `TestCoverageReport`, not caring about the intermediate JSON. Let me know if it would be helpful to have direct JSON access surfaced in the API.

***

The relevant method is [`codeCoverageReport(ignoreCoveredRegions:reportProgress:)`](https://sdggiesbrecht.github.io/SDGSwift/🇨🇦EN/Types/PackageRepository/Methods/codeCoverageReport(ignoreCoveredRegions:reportProgress:).html).

To use it, you would simply import the basic `SDGSwift` product, and do something like this:

```swift
import SDGSwift

let myPackage = PackageRepository(at: URL(fileURLWithPath: "path/to/a/local/package/repository/root"))

// A closure that prints progress to the console as it happens.
// This is just so users can tell it is still working and has not died.
let reportProgress: (String) -> Void = { print($0) }

// Make sure the JSON report has been produced.
// (If “swift test” has already been invoked some other way, this isn’t necessary.)
myPackage.test(reportProgress: reportProgress)

let coverage = try myPackage.codeCoverageReport(
  ignoreCoveredRegions: false,
  reportProgress: reportProgress
).get()

// Then do something with it...
guard let coverage = coverage else {
  fatalError("There is no coverage data in SwiftPM. Are you sure you have run the tests?")
}
for fileCoverage in coverage.files {
  print("File:", fileCoverage.file.path)
  let untested = fileCoverage.regions.lazy.filter({ $0.count == 0 }).count
  print("Number of untested regions: \(untested)\n")
}
```

As a more involved example, the motivating client for this functionality uses it [like this](https://github.com/SDGGiesbrecht/Workspace/blob/master/Sources/WSTesting/PackageRepository.swift#L353-L423). (The initial loading of the report [is higher up in the file](https://github.com/SDGGiesbrecht/Workspace/blob/abb284d1a1df1c1f6f55831ac704646b185eda93/Sources/WSTesting/PackageRepository.swift#L276-L296).)

**Comment by RLovelett** [comment]
Thank you for the very detailed response. This gets me very far down the road (or at least I think so right now).

I modified your `for` loop to:

```swift
for fileCoverage in coverage.files {
    print("File:", fileCoverage.file.path)
    let fileData = try String(contentsOf: fileCoverage.file, encoding: .utf8)
    for region in fileCoverage.regions {
        print(region.region)
        let foo = fileData.scalars[region.region]
        let bar = String(foo)
        print(bar)
    }
}
```

I've run a test against this simple file:

```swift
func add<I: FixedWidthInteger>(a: I, b: I) -> I {
    return a + b
}
```

And it outputs:

```
File: /Users/rlovelett/Source/simple/Sources/Library/sample.swift
Index(_rawBits: 3538945)..<Index(_rawBits: 4325633)
return a + b
```

Excellent.

### Follow Up Question

The `llvm-cov` JSON provides "higher level" metrics like lines, functions and instantiations. What API is the `codeCoverageReport` pulling from? Would it happen to provide these same metrics?

**Comment by SDGGiesbrecht** [comment]
The JSON does also contain some summary information like that, but so far this library just ignores it.

The raw JSON report is extremely clumsy. What you get from `TestCoverageReport` has been significantly cleaned up. Most importantly, external dependencies have been filtered out—the raw summary percentage in the JSON tells you how much of your entire package graph has been tested by the top‐level package’s tests, which is a totally useless metric. Some other fixes have been applied as well. Adjacent or overlapping ranges have been joined. Whitespace margins have been stripped. Various other errors have been corrected, such as when an `else` keyword itself is reported untested even though its attached code block has a non‐zero execution count.

If I were trying to produce a meaningful summary, I would not trust the numbers from the JSON report, but rather derive metrics of my own from the repaired ranges. Files and lines would be easy to measure. Functions would be more involved, but to do it I would turn to `SwiftSyntax`, look up the relevant types of nodes, and compare their source ranges against the ranges reported here.

In case you would still rather fish it from the JSON, the closest thing to a specification about its structure is [this section of its source code in LLVM](https://github.com/llvm-mirror/llvm/blob/1c5d0ae75b26d0aa7e158bdbfc3358466fbb7188/tools/llvm-cov/CoverageExporterJson.cpp#L15-L39).

**Comment by RLovelett** [comment]
I'm not married to to the JSON at all. I mostly just want a way to easily get coverage on a per line basis. The other breakdowns of functions and instantiations are just "nice to have". It was merely a way to frame or reference the discussion on my side because I know so little about the subject.

The suggestion of integrating it with SwiftSyntax is an interesting one. I'll see if I can use that to get the line/function metrics I am looking for.

**Comment by RLovelett** [comment]
I am going to close this because I think I have a plan on how to do this all. Thank you @SDGGiesbrecht for discussing and providing code examples. Very helpful.

**Comment by Dracks** [comment]
hi @RLovelett I found this ticket, did you get it working? can you share the project? thanks!
