### ISSUE TITLE
programatically generate mock packages

### ISSUE THREAD

**Issue by kelvin13** [SDGGiesbrecht/SDGSwift#387]
is there a way to programmatically mock up packages? meaning i would like to *generate* some package which depends on another (local repository) package, for symbol inspection purposes. then i could `swift run` it to dump out the imported symbols, and feed that into my codegen system.

```
real-package/
    Package.swift 
    Sources/
        my-library-module/
            definitions.swift

mock-package/
    Package.swift
    Sources/
        inspector/
            main.swift
```

``` swift
// real-package/Sources/my-library-module/definitions.swift 

enum Foo 
{
    static 
    let types:[MyProtocol.Type] = [Bar.self, Baz.self]
}
```

``` swift
// mock-package/Sources/inspector/main.swift 

@testable import MyLibraryModule

for type:MyProtocol.Type in Foo.types 
{
    print("\(type)")
    ...
}
```

``` swift
// mock-package/Package.swift 
// swift-tools-version: ...

let package ....

    dependencies: 
    [
        .package(path: "../real-package")
    ]
    ...
```

ideally, i would generate `mock-package/Sources/inspector/main.swift` as a `String` from swift, and possibly generate `mock-package/Package.swift` as a typed `PackageDescription.Package` (or less ideally, a `String`), and then have `SDGSwift` generate the mock package and run the `inspector` target. 

maybe, it would look like this: 

```swift 
let inspectorSource:String = generateInspectorSource()

let mockPackage:<???> = .init(products: [.executable(targets: ["inspector"])], 
    dependencies: [.package(path: "../real-package")], 
    targets: 
    [
        .executableTarget("inspector", sources: [inspectorSource]) // the source file contents, not a file path!
    ])

mockPackage.run("inspector")
```

**Comment by SDGGiesbrecht** [comment]
I am terribly sorry I did not see this issue sooner. If GitHub really did try to notify me, I must have mistaken it for an issue in `swift‐package‐manager` and left it for someone else to answer. A two‐month response time is inexcusable. If it ever happens again, feel free to ping me a second time much sooner.

There is currently nothing here for generating packages beyond a rudimentary wrapper for `swift package init`.

SwiftPM itself has recently added some CLI commands for editing packages. Wrappers for those would be welcome in `SDGSwift` if someone wants to contribute them.

More involved utilities would also be welcome, provided they are of generalized usefulness. But SwiftPM itself has mostly outgrown the need for the `SDGSwiftPackageManager` wrapper anymore, as the APIs of its library product are much easier to use than they once were. SwiftPM may already provide the API you need directly.

**Comment by kelvin13** [comment]
hah it’s okay… i ended up solving the problem the way you described. it’s unfortunate though that linking to `libSwiftPM.so` includes the whole 50 MB SPM binary in the final product, just because one of its package plugins depends on it though :/

**Comment by SDGGiesbrecht** [comment]
Did you try the `SwiftPM-auto` product? It is identical, but statically linked by default. Then you should be able to enable LTO and dead stripping for the build to trim it down significantly.
